// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBwBLbh-WntuGcgNPTeo2FtH2uA8Tqit0I',
    appId: '1:299976105843:web:68a7c2f95cbf6c6826af06',
    messagingSenderId: '299976105843',
    projectId: 'vox-city',
    authDomain: 'vox-city.firebaseapp.com',
    storageBucket: 'vox-city.firebasestorage.app',
    measurementId: 'G-4T989XWNE7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD6j19n2b6N7XmlvsGv_dOFmmGWo0lPTDo',
    appId: '1:299976105843:android:43f1304cc19a452e26af06',
    messagingSenderId: '299976105843',
    projectId: 'vox-city',
    storageBucket: 'vox-city.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAgxiy3AQjGTYFV0iqn35Wsu403z_Vo4Z8',
    appId: '1:299976105843:ios:40d378f9c6529ad326af06',
    messagingSenderId: '299976105843',
    projectId: 'vox-city',
    storageBucket: 'vox-city.firebasestorage.app',
    iosBundleId: 'com.example.voxcity',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAgxiy3AQjGTYFV0iqn35Wsu403z_Vo4Z8',
    appId: '1:299976105843:ios:40d378f9c6529ad326af06',
    messagingSenderId: '299976105843',
    projectId: 'vox-city',
    storageBucket: 'vox-city.firebasestorage.app',
    iosBundleId: 'com.example.voxcity',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBwBLbh-WntuGcgNPTeo2FtH2uA8Tqit0I',
    appId: '1:299976105843:web:ec14ad952390698f26af06',
    messagingSenderId: '299976105843',
    projectId: 'vox-city',
    authDomain: 'vox-city.firebaseapp.com',
    storageBucket: 'vox-city.firebasestorage.app',
    measurementId: 'G-W2GKKJ8NKN',
  );

}